version: 2.1

jobs:
  remote_docker:
    parameters:
      docker-version:
        type: string
        description: "See https://circleci.com/docs/building-docker-images/#docker-version"
    docker:
      - image: cimg/base:current
    # NOTE: also defaults to large
    resource_class: "large"
    steps:
      - setup_remote_docker:
          version: << parameters.docker-version >>
      - run: docker system info

workflows:
  main:
    jobs:
      remote_docker:
        matrix:
          parameters:
            docker-version:
              - 20.10.24
              # Docker v24.x not supported
              - 24.0.2
