version: 2.1

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.7-node
    resource_class: medium
    parameters:
      docker:
        type: string
    steps:
      - checkout
      - setup_remote_docker:
          version: << parameters.docker >>
      - run: |
          docker --version
          docker-compose --version
      - run:
          name: build Docker image
          command: |
            docker image build --no-cache -t customruby .
      - run:
          name: list images
          command: docker image ls

workflows:
  main:
    jobs:
      - build:
          matrix:
            parameters:
              docker:
                - 20.10.14
                - 20.10.24
                - docker23
                - edge
                
